// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mymap.proto

package stream.performance.mytest;

public final class mymap {
  private mymap() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MymapOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated string mykey = 1;
    /**
     * <code>repeated string mykey = 1;</code>
     */
    java.util.List<java.lang.String>
    getMykeyList();
    /**
     * <code>repeated string mykey = 1;</code>
     */
    int getMykeyCount();
    /**
     * <code>repeated string mykey = 1;</code>
     */
    java.lang.String getMykey(int index);
    /**
     * <code>repeated string mykey = 1;</code>
     */
    com.google.protobuf.ByteString
        getMykeyBytes(int index);

    // repeated string myvalue = 2;
    /**
     * <code>repeated string myvalue = 2;</code>
     */
    java.util.List<java.lang.String>
    getMyvalueList();
    /**
     * <code>repeated string myvalue = 2;</code>
     */
    int getMyvalueCount();
    /**
     * <code>repeated string myvalue = 2;</code>
     */
    java.lang.String getMyvalue(int index);
    /**
     * <code>repeated string myvalue = 2;</code>
     */
    com.google.protobuf.ByteString
        getMyvalueBytes(int index);
  }
  /**
   * Protobuf type {@code tutorial.Mymap}
   */
  public static final class Mymap extends
      com.google.protobuf.GeneratedMessage
      implements MymapOrBuilder {
    // Use Mymap.newBuilder() to construct.
    private Mymap(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Mymap(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Mymap defaultInstance;
    public static Mymap getDefaultInstance() {
      return defaultInstance;
    }

    public Mymap getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Mymap(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                mykey_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              mykey_.add(input.readBytes());
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                myvalue_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              myvalue_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          mykey_ = new com.google.protobuf.UnmodifiableLazyStringList(mykey_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          myvalue_ = new com.google.protobuf.UnmodifiableLazyStringList(myvalue_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stream.performance.mytest.mymap.internal_static_tutorial_Mymap_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stream.performance.mytest.mymap.internal_static_tutorial_Mymap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              stream.performance.mytest.mymap.Mymap.class, stream.performance.mytest.mymap.Mymap.Builder.class);
    }

    public static com.google.protobuf.Parser<Mymap> PARSER =
        new com.google.protobuf.AbstractParser<Mymap>() {
      public Mymap parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Mymap(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Mymap> getParserForType() {
      return PARSER;
    }

    // repeated string mykey = 1;
    public static final int MYKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList mykey_;
    /**
     * <code>repeated string mykey = 1;</code>
     */
    public java.util.List<java.lang.String>
        getMykeyList() {
      return mykey_;
    }
    /**
     * <code>repeated string mykey = 1;</code>
     */
    public int getMykeyCount() {
      return mykey_.size();
    }
    /**
     * <code>repeated string mykey = 1;</code>
     */
    public java.lang.String getMykey(int index) {
      return mykey_.get(index);
    }
    /**
     * <code>repeated string mykey = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMykeyBytes(int index) {
      return mykey_.getByteString(index);
    }

    // repeated string myvalue = 2;
    public static final int MYVALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList myvalue_;
    /**
     * <code>repeated string myvalue = 2;</code>
     */
    public java.util.List<java.lang.String>
        getMyvalueList() {
      return myvalue_;
    }
    /**
     * <code>repeated string myvalue = 2;</code>
     */
    public int getMyvalueCount() {
      return myvalue_.size();
    }
    /**
     * <code>repeated string myvalue = 2;</code>
     */
    public java.lang.String getMyvalue(int index) {
      return myvalue_.get(index);
    }
    /**
     * <code>repeated string myvalue = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMyvalueBytes(int index) {
      return myvalue_.getByteString(index);
    }

    private void initFields() {
      mykey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      myvalue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < mykey_.size(); i++) {
        output.writeBytes(1, mykey_.getByteString(i));
      }
      for (int i = 0; i < myvalue_.size(); i++) {
        output.writeBytes(2, myvalue_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < mykey_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(mykey_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getMykeyList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < myvalue_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(myvalue_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getMyvalueList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static stream.performance.mytest.mymap.Mymap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static stream.performance.mytest.mymap.Mymap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static stream.performance.mytest.mymap.Mymap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static stream.performance.mytest.mymap.Mymap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static stream.performance.mytest.mymap.Mymap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static stream.performance.mytest.mymap.Mymap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static stream.performance.mytest.mymap.Mymap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static stream.performance.mytest.mymap.Mymap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static stream.performance.mytest.mymap.Mymap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static stream.performance.mytest.mymap.Mymap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(stream.performance.mytest.mymap.Mymap prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Mymap}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements stream.performance.mytest.mymap.MymapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return stream.performance.mytest.mymap.internal_static_tutorial_Mymap_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return stream.performance.mytest.mymap.internal_static_tutorial_Mymap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                stream.performance.mytest.mymap.Mymap.class, stream.performance.mytest.mymap.Mymap.Builder.class);
      }

      // Construct using mytest.mymap.Mymap.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        mykey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        myvalue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return stream.performance.mytest.mymap.internal_static_tutorial_Mymap_descriptor;
      }

      public stream.performance.mytest.mymap.Mymap getDefaultInstanceForType() {
        return stream.performance.mytest.mymap.Mymap.getDefaultInstance();
      }

      public stream.performance.mytest.mymap.Mymap build() {
        stream.performance.mytest.mymap.Mymap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public stream.performance.mytest.mymap.Mymap buildPartial() {
        stream.performance.mytest.mymap.Mymap result = new stream.performance.mytest.mymap.Mymap(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          mykey_ = new com.google.protobuf.UnmodifiableLazyStringList(
              mykey_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.mykey_ = mykey_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          myvalue_ = new com.google.protobuf.UnmodifiableLazyStringList(
              myvalue_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.myvalue_ = myvalue_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof stream.performance.mytest.mymap.Mymap) {
          return mergeFrom((stream.performance.mytest.mymap.Mymap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(stream.performance.mytest.mymap.Mymap other) {
        if (other == stream.performance.mytest.mymap.Mymap.getDefaultInstance()) return this;
        if (!other.mykey_.isEmpty()) {
          if (mykey_.isEmpty()) {
            mykey_ = other.mykey_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMykeyIsMutable();
            mykey_.addAll(other.mykey_);
          }
          onChanged();
        }
        if (!other.myvalue_.isEmpty()) {
          if (myvalue_.isEmpty()) {
            myvalue_ = other.myvalue_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMyvalueIsMutable();
            myvalue_.addAll(other.myvalue_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        stream.performance.mytest.mymap.Mymap parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (stream.performance.mytest.mymap.Mymap) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string mykey = 1;
      private com.google.protobuf.LazyStringList mykey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMykeyIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          mykey_ = new com.google.protobuf.LazyStringArrayList(mykey_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string mykey = 1;</code>
       */
      public java.util.List<java.lang.String>
          getMykeyList() {
        return java.util.Collections.unmodifiableList(mykey_);
      }
      /**
       * <code>repeated string mykey = 1;</code>
       */
      public int getMykeyCount() {
        return mykey_.size();
      }
      /**
       * <code>repeated string mykey = 1;</code>
       */
      public java.lang.String getMykey(int index) {
        return mykey_.get(index);
      }
      /**
       * <code>repeated string mykey = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMykeyBytes(int index) {
        return mykey_.getByteString(index);
      }
      /**
       * <code>repeated string mykey = 1;</code>
       */
      public Builder setMykey(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMykeyIsMutable();
        mykey_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mykey = 1;</code>
       */
      public Builder addMykey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMykeyIsMutable();
        mykey_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mykey = 1;</code>
       */
      public Builder addAllMykey(
          java.lang.Iterable<java.lang.String> values) {
        ensureMykeyIsMutable();
        super.addAll(values, mykey_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mykey = 1;</code>
       */
      public Builder clearMykey() {
        mykey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mykey = 1;</code>
       */
      public Builder addMykeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMykeyIsMutable();
        mykey_.add(value);
        onChanged();
        return this;
      }

      // repeated string myvalue = 2;
      private com.google.protobuf.LazyStringList myvalue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMyvalueIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          myvalue_ = new com.google.protobuf.LazyStringArrayList(myvalue_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string myvalue = 2;</code>
       */
      public java.util.List<java.lang.String>
          getMyvalueList() {
        return java.util.Collections.unmodifiableList(myvalue_);
      }
      /**
       * <code>repeated string myvalue = 2;</code>
       */
      public int getMyvalueCount() {
        return myvalue_.size();
      }
      /**
       * <code>repeated string myvalue = 2;</code>
       */
      public java.lang.String getMyvalue(int index) {
        return myvalue_.get(index);
      }
      /**
       * <code>repeated string myvalue = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMyvalueBytes(int index) {
        return myvalue_.getByteString(index);
      }
      /**
       * <code>repeated string myvalue = 2;</code>
       */
      public Builder setMyvalue(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMyvalueIsMutable();
        myvalue_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string myvalue = 2;</code>
       */
      public Builder addMyvalue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMyvalueIsMutable();
        myvalue_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string myvalue = 2;</code>
       */
      public Builder addAllMyvalue(
          java.lang.Iterable<java.lang.String> values) {
        ensureMyvalueIsMutable();
        super.addAll(values, myvalue_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string myvalue = 2;</code>
       */
      public Builder clearMyvalue() {
        myvalue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string myvalue = 2;</code>
       */
      public Builder addMyvalueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMyvalueIsMutable();
        myvalue_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Mymap)
    }

    static {
      defaultInstance = new Mymap(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.Mymap)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Mymap_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Mymap_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013mymap.proto\022\010tutorial\"\'\n\005Mymap\022\r\n\005myke" +
      "y\030\001 \003(\t\022\017\n\007myvalue\030\002 \003(\tB\017\n\006mytestB\005myma" +
      "p"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_Mymap_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_Mymap_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Mymap_descriptor,
              new java.lang.String[] { "Mykey", "Myvalue", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
